name: emacs-fusion
version: 25.1
summary: GNU Emacs 25.1
description: An extensible, customizable, free/libre text editor -- and more.
confinement: strict

apps:
  emacs-fusion:
    command: emacs-fusion
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
      - network-bind
  emacsclient-fusion:
    command: emacsclient-fusion
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
  ctags:
    command: ctags
  ebrowse:
    command: ebrowse
  etags:
    command: etags
  grep-changelog:
    command: grep-changelog

parts:
  emacs-fusion:
    plugin: copy
    files:
      emacs-fusion.sh: bin/emacs-fusion
      emacsclient-fusion.sh: bin/emacsclient-fusion
  emacs:
    plugin: autotools
    source: http://ftp.gnu.org/gnu/emacs/emacs-25.1.tar.xz
    source-type: tar
    install-via: prefix
    build-packages:
      - libgif-dev
      - libxpm-dev
      - libjpeg-dev
      - libtiff5-dev
      - libncursesw5-dev
      - libsm-dev
      - libxft-dev
    stage-packages:
      - libgif7
      - libxpm4
      - libjpeg8
      - libtiff5
      - libncursesw5
      - libsm6
      - libxft2
    after:
      - desktop/gtk3
